### ISSUE TITLE
inf

### ISSUE THREAD

**Issue by Wkaiming** [Sakurai07/Checkra1n.py#4]
Without find infinstaller.exe, inf cannot be installed directly, so how to install inf?

cd to the libusb folder after cloning/downloading and copy libusb.dll to c:/windows/system32 and c:/windows/syswow64 (only if 64bit) then run infinstaller.exe from libusb folder and install the .inf file by right clicking. AFter that copy Libusb0.sys to c:/windows/system32/Drivers and c:/windows/syswow64 (only if 64bit)

**Comment by wynwxst** [comment]
@Wkaiming try https://www.smallcab.net/download/programme/xm-07/how-to-install-libusb-driver.pdf

**Comment by wynwxst** [comment]
i'll update libusb for the latest version

**Comment by wynwxst** [comment]
actually there is a lot of room for cleaning the code up, expect a full clean up in the next 2 days @Wkaiming

**Comment by wynwxst** [comment]
tell if you have more issues after the clean up
